### ISSUE TITLE
Alias to_s on Url objects to short_url

### ISSUE THREAD

**Issue by cableray** [philnash/bitly#48]
I'm thinking that to_s on the url objects should return the short url.

**Comment by philnash** [comment]
Sorry for leaving such an old issue for such a long time.

I don't know why Rails would show the short_url when using `to_s` however I don't think that's the correct behaviour. There are many ways of starting with one type of URL and ending up with the URL object that the short_url isn't always the obvious thing you were after so preferring it in `to_s` might be counter intuitive. I'd rather each version of the URL was only available as it's attribute.
