### ISSUE TITLE
INVALID_APIKEY with Generic Access Token

### ISSUE THREAD

**Issue by philgyford** [philnash/bitly#50]
Sorry, I must be doing something wrong, as I'm following the example but when trying to shorten a URL I keep getting an error. I do this:

    Bitly.use_api_version_3

    Bitly.configure do |config|
        config.api_version = 3
        config.login = 'mylogin'
        config.api_key = 'myGenericAccessToken'
    end

    bitly_client = Bitly.client
    #<Bitly::V3::Client:0x007fc87589bdc8 @default_query_opts={:login=>"mylogin", :apiKey=>"myGenericAccessToken"}> 

    u = bitly_client.shorten("http://www.example.org")

That gets me:

    BitlyError: INVALID_APIKEY - '500'
	from /Users/phil/.rvm/gems/ruby-1.9.3-p392/gems/bitly-0.9.0/lib/bitly/v3/client.rb:141:in `get'
	from /Users/phil/.rvm/gems/ruby-1.9.3-p392/gems/bitly-0.9.0/lib/bitly/v3/client.rb:41:in `shorten'
	from (irb):17
	from /Users/phil/.rvm/rubies/ruby-1.9.3-p392/bin/irb:16:in `<main>'

Anything obvious I've done wrong?

**Comment by musixite** [comment]
Don't use the deprecated API key, use oAuth on Bitly settings.

**Comment by sachinswagh-opcito** [comment]
@jianbo : How did you solve it? I am facing same issue with 1.1.1 also.

**Comment by sachinswagh-opcito** [comment]
@philnash : I am facing INVALID_ARG_ACCESS_TOKEN - '500' with bitly 1.1.1 also. Would you please help?

**Comment by philnash** [comment]
Can you share the code you are using that is generating that error? It looks like an error coming from the Bitly API rather than the gem, though is probably how you are using it. I can't debug without an idea of what you're doing though.
