### ISSUE TITLE
Use HTTPS not HTTP when communicating with api.bit.ly

### ISSUE THREAD

**Issue by dmz006** [philnash/bitly#56]
While setting up the bitly gem I noticed that the API URL is set to:
API_URL     = 'http://api.bit.ly/'

However when reviewing api.bitly.com, in their best practices I see their example of a valid API call to shorten the link uses:
https://api-ssl.bitly.com/

Is there any plan on updating this gem to use the https link so api keys aren't transmitted in cleartext?

**Comment by philnash** [comment]
Well, this may have been a long time ago, but this has now been fixed in 301aa7a. Noone should be using the v2 API anyway, but if they do, next time I get a release out, it will use the https URL.
