### ISSUE TITLE
Can't retrieve the short url in the view?!

### ISSUE THREAD

**Issue by musixite** [philnash/bitly#64]
Hello there,

I've been scratching my head for the last 2 hours and I can't find what I'm doing wrong.

Rails 4.2
```
gem 'bitly', '~> 0.10.4'
```

My initializer uses oAuth:
```
Bitly.use_api_version_3

Bitly.configure do |config|
  config.api_version = 3
  config.access_token = "0a9e6c23bb42efd17feffa3266dbd4aa7ec8d045"
end
```

Now when I'm trying to get in the view the short_url, I have in my controller show
```
@url = Bitly.client.shorten('http://www.google.com')
@short_url = @url.short_url
```

Now this is where it gets confusing.
- I'm able to shorten a link.
- It gets in the Bit.ly website with the proper short url.
- but I get a no-method error on my show page when calling @short_url in the view.

Why is that? 
Where is my mistake?

Thanks!
- Vincent

**Comment by philnash** [comment]
Hey Vincent,

How are you calling @short_url in the view?

**Comment by musixite** [comment]
I assumed I would just call @url.shor_url but this doesn't work

**Comment by philnash** [comment]
Can you flesh the code out a bit for me, please? Could I see what your controller action and your view does, please? Otherwise it's a bit hard to tell what's going on. Thanks.

**Comment by musixite** [comment]
Hey Phil,

Thanks for helping me out. Here's what I have.

## gemfile

```
gem 'bitly', '~> 0.10.4'
```

## Initializer bitly.rb

```
Bitly.use_api_version_3

Bitly.configure do |config|
  config.api_version = 3
  config.access_token = "0a9e6c23bb42efd17feffa3266dbd4aa7ec8d045"
end
```

For testing purposes, I simply added this in my controller 

```
class StoriesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, except: [:toc, :show, :comments]

  layout "backend/index"

def show
    render :layout => "frontend/index"
    @story = Story.find(params[:id])
    @comment = Comment.new

   # Bitly add
    @bitly = Bitly.client.shorten('http://www.liberation.fr')
    @short_url = @bitly.short_url

  end
end
```

When I call the show story action page, the billy url gets added to the billy.com backend (I can see the link and the billy short link)

![screen shot 2015-02-17 at 10 03 37 am](https://cloud.githubusercontent.com/assets/411987/6230271/4639e03a-b68c-11e4-985e-c9e13af07742.png)

I then called the @short_url variable in my Stories show view with:
```
<p class='bitly-short-link'><%= @short_url %></p>
```

This is where I'm stuck. It doesn't show anything. So what am I missing?!

Thanks again for your help!
- Vincent

**Comment by philnash** [comment]
Hey Vincent,

I think the problem is that you're rendering the view before you set your instance variables. That might not show up when you're getting things from the database, but making an external API call is going to take a bit of time and the `@short_url` instance variable won't be set by the time the view gets rendered.

Try moving the line `render :layout => "frontend/index"` to the bottom of your action and see what happens.

**Comment by musixite** [comment]
Good catch, that was it!

Thank you so much for solving this, the day starts right :)
- Vincent

**Comment by philnash** [comment]
Excellent! Hope the rest of the app goes well!
