### ISSUE TITLE
passing title when creating link

### ISSUE THREAD

**Issue by vibhoo** [philnash/bitly#66]
Hey! would love to know, how can I pass the title for the long URL, so that in future I can search based on the title & get short link

Thanks

**Comment by philnash** [comment]
Hi @vibhoo, what do you mean exactly? Is this is a function of the Bitly API itself or do you mean you would like to see it as part of the gem?

**Comment by vibhoo** [comment]
@philnash Bitly API has this functionality to provide title for the long URL which we are trying to shorten I think that this functionality is missing in the gem

**Comment by philnash** [comment]
Are you looking for an implementation of the [link_save](https://dev.bitly.com/links.html#v3_link_save) method?

This is one of the newer ones (at least, compared to this library). I could look into it, though if you have time to make a pull request that would be awesome. I'd be willing to help out if you wanted to look into it.

**Comment by philnash** [comment]
This is now possible in version 2 of the gem. Please check the docs for creating a new Bitlink.
