### ISSUE TITLE
Passing parameters to Bitly.client

### ISSUE THREAD

**Issue by s8sachin** [philnash/bitly#70]
According to https://dev.bitly.com/link_metrics.html#v3_link_clicks,
we can send multiple parameters like link, unit, etc.
i am actually looking for **Clicks by Day**
i tried `Bitly.client.clicks("http://bit.ly/2tAL7YS").clicks_by_day`, works fine
but i need to change **Time Zone** value
i tried this `Bitly.client.info({"link" =>"http://bit.ly/2tAL7YS", "timezone" => -6}).clicks_by_day`
and i am getting error. Please help

**Comment by philnash** [comment]
The Bitly version 3 API is no longer available. Please check out version 2 of this gem which works with the version 4 API.
