### ISSUE TITLE
Modernise and rewrite this entire library

### ISSUE THREAD

**Issue by philnash** [philnash/bitly#73]
This gem was written such a long time ago. It's more than time for an update. And I don't just mean deprecate the (surely by now) long gone v2 API.

I am adding this issue as a commitment that I am going to rewrite this gem from scratch. It's going to be more consistent, more up to date and just generally better all round. All you Bitly API calling dreams will come true.

**Comment by Deuteu** [comment]
All by yourself or is there any branch on which we can follow this (maybe even help you) ?

**Comment by philnash** [comment]
Oh! I have started this in the v2 branch (as in, version 2 of this library) but I hadn't seen that the v4 Bitly API had been released. My initial work was on the v3 API, but I'm not a whole distance into it just yet.

Will investigate the V4 API. I also imagine that supporting v3 will be important.

**Comment by uybinh** [comment]
I'm working on my project, and want to use this gem.
Is there any way we can help with?

**Comment by philnash** [comment]
This is done with the release of version 2.0.0.
