### ISSUE TITLE
API V4 support

### ISSUE THREAD

**Issue by shimar** [philnash/bitly#76]
Hi.

The [bitly documents](https://dev.bitly.com/v4_documentation.html) say that
> API V3 will be deactivated on March 1, 2020. 

Are there any plan to support API V4 in this gem?

**Comment by sevenseacat** [comment]
We use super-basic functionality from this gem (basically just creating short URLs) so I'm working on adding support for that using the V4 API now. Will open a PR when complete.

**Comment by VanPaitin** [comment]
Hi @sevenseacat , when do you think the PR will be ready.

**Comment by sevenseacat** [comment]
https://github.com/philnash/bitly/pull/77

We're using it in production, so it's good for the basic functionality we need.

**Comment by philnash** [comment]
Hey everyone,

I have put together a completely new version of the gem to support version 4. It's released as version 2.0.0.beta.1 right now: https://rubygems.org/gems/bitly/versions/2.0.0.beta.1.

I'd appreciate if you could take it for a spin and let me know if it works for your.

Thanks!

**Comment by tomwilshere** [comment]
@philnash working fine for us - just a note that the current documentation on master is for `2.0.0.beta.1` but the published gem is `1.1.2` so a newcomer coming to this library and following the instructions would receive an error.

**Comment by philnash** [comment]
Thanks to those who have taken a look so far. I just pushed version 2.0.0.beta.2 which changes the loading mechanism to autoload. Would appreciate any time you have to check it out.

Thanks @tomwilshere, I appreciate the docs have gone out of order, but by now if you try to use the old gem it's going to break against the shut down API anyway. With a :+1: or two quickly, and a couple more pages of documentation to write, I can get this fully released and we can move beyond v1 of the gem and v2 and v3 of the Bitly API.

**Comment by clarkritchie** [comment]
👍  Just installed this in our dev environment and it seems to work great.  Thanks!

**Comment by sevenseacat** [comment]
We're also using 2.0.0.beta.2 in our code and it's going well 👍

**Comment by philnash** [comment]
Amazing. I will look to release this tomorrow as the final version 2. Thanks to all who tested.

**Comment by philnash** [comment]
Version 2.0.0 is released!

Go forth and use Bitly API v4. And let me know if anything goes wrong or if I missed a spot.
