### ISSUE TITLE
Undefined method "use_api_version_3" for Bitly:Module

### ISSUE THREAD

**Issue by MwMaki** [philnash/bitly#79]
After upgrading the rails to 5 and ruby to 2.5 I started to receive this error,
`/config/initializers/bitly.rb:1`:in  <top (required)>: undefined method "use_api_version_3" for Bitly:Module (NoMethodError)
any idea how to fix this issue ?

this is how the initializer file `config/initializers/bitly.rb` looks like
```ruby 
Bitly.use_api_version_3

Bitly.configure do |config|
  config.api_version = 3
  config.access_token = Rails.application.secrets["bitly"]["access_token"]
end

```

**Comment by philnash** [comment]
Is it possible that you upgraded `bitly` during this upgrade process too? Version 2  is a breaking change and no longer uses the version 3 API (which is deprecated), and implements the [version 4 API](https://dev.bitly.com/api-reference) instead.

You can roll back to the version you were using, but I would recommend upgrading as Bitly plans to shut down the V3 API soon. The documentation for the gem has been improved with the new version though, so hopefully you can upgrade your code easily. Let me know if you have any issues with it.

**Comment by MwMaki** [comment]
Thank you. this is very helpful.
